import{a as f}from"./assets/vendor-DXmaTlaC.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const l of n.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function o(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=o(e);fetch(e.href,n)}})();const m="49228326-f0295c59acbd8047419a0b87e",y="https://pixabay.com/api/";let s=1,p="";const g=document.getElementById("searchBtn"),h=document.getElementById("searchQuery"),i=document.getElementById("gallery"),c=document.getElementById("loadMoreBtn"),d=document.getElementById("loadingSpinner");g.addEventListener("click",()=>{p=h.value,s=1,i.innerHTML="",u()});c.addEventListener("click",()=>{s+=1,u()});async function u(){try{d.style.display="block";const t=await f.get(y,{params:{key:m,q:p,page:s,per_page:40}}),r=t.data.hits,o=t.data.totalHits;s*40>=o?(c.style.display="none",i.innerHTML+="<p>We're sorry, but you've reached the end of search results</p>"):c.style.display="block",L(r),E()}catch(t){console.error("Error fetching images:",t)}finally{d.style.display="none"}}function L(t){const r=t.map(o=>`<div class="gallery-item">
              <img src="${o.webformatURL}" alt="${o.tags}" data-large="${o.largeImageURL}" />
              <div class="info">
          <p>Likes: ${o.likes}</p>
          <p>Views: ${o.views}</p>
          <p>Comments: ${o.comments}</p>
          <p>Downloads: ${o.downloads}</p>
        </div>
            </div>`).join("");i.innerHTML+=r,b()}function b(){new SimpleLightbox(".gallery-item img",{captionsData:"alt",captionDelay:250}).refresh()}function E(){const t=i.lastElementChild;if(t){const{top:r}=t.getBoundingClientRect();window.scrollBy({top:r+t.offsetHeight*2,behavior:"smooth"})}}
//# sourceMappingURL=index.js.map
